# Generated by Django 4.2.9 on 2024-01-26 09:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='archives',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('file', models.FileField(upload_to='')),
                ('type', models.CharField(max_length=255)),
                ('entity', models.CharField(max_length=255)),
                ('tips', models.TextField()),
            ],
        ),
    ]
