# Generated by Django 4.2.9 on 2024-01-27 18:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_archives_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archives',
            name='tips',
            field=models.CharField(max_length=225),
        ),
        migrations.AlterField(
            model_name='archives',
            name='type',
            field=models.CharField(choices=[('export', 'export'), ('import', 'import')], max_length=10),
        ),
    ]
